<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FPTEnglishRAG.Application\FPTEnglishRAG.Application.csproj" />
    <ProjectReference Include="..\FPTEnglishRAG.Domain\FPTEnglishRAG.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
