// File: src/FPTEnglishRAG.Application/Services/CitationValidator.cs

using System.Collections.Generic;
using System.Text.RegularExpressions;
using FPTEnglishRAG.Application.Abstractions;
using FPTEnglishRAG.Application.DTOs;

namespace FPTEnglishRAG.Application.Services;

/// <summary>
/// Validates and maps citations generated by the AI model back to the original retrieved chunks.
/// This is a pure functional service without external dependencies or I/O.
/// </summary>
public sealed class CitationValidator : ICitationValidator
{
    // Regex to match citation tags like [S1], [s2], [S10], etc.
    // We make the 'S' case-insensitive just in case the model outputs [s1].
    private static readonly Regex s_citationRegex = new Regex(@"\[S(\d+)\]", RegexOptions.Compiled | RegexOptions.IgnoreCase);

    /// <inheritdoc/>
    public List<Citation> ValidateAndMap(string modelOutput, IReadOnlyList<RetrievedChunk> retrievedChunks)
    {
        var result = new List<Citation>();

        if (string.IsNullOrWhiteSpace(modelOutput))
        {
            return result;
        }

        var matches = s_citationRegex.Matches(modelOutput);
        var seenLabels = new HashSet<string>();

        foreach (Match match in matches)
        {
            var label = match.Value.ToUpperInvariant(); // Normalize to [S1]
            
            // Avoid duplicates
            if (seenLabels.Contains(label))
            {
                continue;
            }

            // Extract the numeric part
            if (int.TryParse(match.Groups[1].Value, out var index))
            {
                // The label is 1-based, chunks array is 0-based
                var chunkIndex = index - 1;

                // Validate index is within bounds of retrieved chunks
                if (chunkIndex >= 0 && chunkIndex < retrievedChunks.Count)
                {
                    var chunkId = retrievedChunks[chunkIndex].ChunkId;
                    
                    // Note: Citation DTO uses the inner label text, e.g., "S1", not "[S1]".
                    // Let's strip the brackets to get "S1".
                    var rawLabel = $"S{index}";
                    
                    result.Add(new Citation(rawLabel, chunkId));
                    seenLabels.Add(label);
                }
            }
        }

        return result;
    }
}
