// <auto-generated />
using System;
using FPTEnglishRAG.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FPTEnglishRAG.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RagDbContext))]
    partial class RagDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FPTEnglishRAG.Infrastructure.Persistence.Entities.ChunkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "Ordinal")
                        .IsUnique();

                    b.ToTable("Chunks", (string)null);
                });

            modelBuilder.Entity("FPTEnglishRAG.Infrastructure.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("FPTEnglishRAG.Infrastructure.Persistence.Entities.EmbeddingEntity", b =>
                {
                    b.Property<Guid>("ChunkId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dimensions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IndexVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Vector")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("ChunkId");

                    b.HasIndex("Model", "Dimensions", "IndexVersion");

                    b.ToTable("Embeddings", (string)null);
                });

            modelBuilder.Entity("FPTEnglishRAG.Infrastructure.Persistence.Entities.ChunkEntity", b =>
                {
                    b.HasOne("FPTEnglishRAG.Infrastructure.Persistence.Entities.DocumentEntity", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("FPTEnglishRAG.Infrastructure.Persistence.Entities.EmbeddingEntity", b =>
                {
                    b.HasOne("FPTEnglishRAG.Infrastructure.Persistence.Entities.ChunkEntity", "Chunk")
                        .WithOne("Embedding")
                        .HasForeignKey("FPTEnglishRAG.Infrastructure.Persistence.Entities.EmbeddingEntity", "ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chunk");
                });

            modelBuilder.Entity("FPTEnglishRAG.Infrastructure.Persistence.Entities.ChunkEntity", b =>
                {
                    b.Navigation("Embedding");
                });

            modelBuilder.Entity("FPTEnglishRAG.Infrastructure.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
